# Generated by Django 6.0.3 on 2026-04-06 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_diversification', models.TextField(blank=True, default='')),
                ('instructions_liquidity', models.TextField(blank=True, default='')),
                ('instructions_fees', models.TextField(blank=True, default='')),
                ('instructions_tax', models.TextField(blank=True, default='')),
                ('instructions_risk', models.TextField(blank=True, default='')),
                ('instructions_performance', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exposure_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('exposure_group', models.CharField(choices=[('fixed_income', 'Fixed Income'), ('equity', 'Equity'), ('real_estate', 'Real Estate'), ('crypto', 'Crypto')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Economic Exposures',
                'db_table': 'economic_exposure',
                'ordering': ['exposure_code'],
            },
        ),
        migrations.CreateModel(
            name='IssuerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_diversification', models.TextField(blank=True, default='')),
                ('instructions_liquidity', models.TextField(blank=True, default='')),
                ('instructions_fees', models.TextField(blank=True, default='')),
                ('instructions_tax', models.TextField(blank=True, default='')),
                ('instructions_risk', models.TextField(blank=True, default='')),
                ('instructions_performance', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer_type_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'issuer_type',
                'ordering': ['issuer_type_code'],
            },
        ),
        migrations.CreateModel(
            name='TaxProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_diversification', models.TextField(blank=True, default='')),
                ('instructions_liquidity', models.TextField(blank=True, default='')),
                ('instructions_fees', models.TextField(blank=True, default='')),
                ('instructions_tax', models.TextField(blank=True, default='')),
                ('instructions_risk', models.TextField(blank=True, default='')),
                ('instructions_performance', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_profile_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'tax_profile',
                'ordering': ['tax_profile_code'],
            },
        ),
        migrations.CreateModel(
            name='Issuer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_diversification', models.TextField(blank=True, default='')),
                ('instructions_liquidity', models.TextField(blank=True, default='')),
                ('instructions_fees', models.TextField(blank=True, default='')),
                ('instructions_tax', models.TextField(blank=True, default='')),
                ('instructions_risk', models.TextField(blank=True, default='')),
                ('instructions_performance', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer_code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('issuer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issuers', to='refdata.issuertype')),
            ],
            options={
                'db_table': 'issuer',
                'ordering': ['issuer_code'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_diversification', models.TextField(blank=True, default='')),
                ('instructions_liquidity', models.TextField(blank=True, default='')),
                ('instructions_fees', models.TextField(blank=True, default='')),
                ('instructions_tax', models.TextField(blank=True, default='')),
                ('instructions_risk', models.TextField(blank=True, default='')),
                ('instructions_performance', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_code', models.CharField(max_length=64, unique=True)),
                ('instrument_kind', models.CharField(choices=[('listed', 'Listed'), ('fixed_income', 'Fixed Income'), ('fund', 'Fund'), ('crypto', 'Crypto'), ('other', 'Other')], max_length=32)),
                ('short_name', models.CharField(max_length=255)),
                ('long_name', models.CharField(blank=True, default='', max_length=512)),
                ('cnpj', models.CharField(blank=True, default='', max_length=32)),
                ('b3_listed', models.BooleanField(blank=True, null=True)),
                ('is_bdr', models.BooleanField(blank=True, null=True)),
                ('yearly_fee_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('performance_fee_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('has_fgc', models.BooleanField(blank=True, null=True)),
                ('requires_expiry_date', models.BooleanField(default=False)),
                ('requires_issuer_or_issuer_type', models.BooleanField(default=False)),
                ('economic_exposure_weights_json', models.JSONField(blank=True, null=True)),
                ('issuer_type_weights_json', models.JSONField(blank=True, null=True)),
                ('primary_economic_exposure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates_primary', to='refdata.economicexposure')),
                ('issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='refdata.issuer')),
                ('primary_issuer_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates_primary', to='refdata.issuertype')),
                ('tax_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='refdata.taxprofile')),
            ],
            options={
                'db_table': 'instrument_template',
                'ordering': ['template_code'],
            },
        ),
        migrations.AddIndex(
            model_name='issuer',
            index=models.Index(fields=['issuer_type'], name='idx_issuer_issuer_type_id'),
        ),
        migrations.AddIndex(
            model_name='instrumenttemplate',
            index=models.Index(fields=['tax_profile'], name='idx_it_tax_profile_id'),
        ),
        migrations.AddIndex(
            model_name='instrumenttemplate',
            index=models.Index(fields=['primary_economic_exposure'], name='idx_it_prim_econ_exp_id'),
        ),
        migrations.AddIndex(
            model_name='instrumenttemplate',
            index=models.Index(fields=['primary_issuer_type'], name='idx_it_prim_issuer_type_id'),
        ),
        migrations.AddIndex(
            model_name='instrumenttemplate',
            index=models.Index(fields=['issuer'], name='idx_it_issuer_id'),
        ),
        migrations.AddConstraint(
            model_name='instrumenttemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('economic_exposure_weights_json__isnull', True), ('primary_economic_exposure__isnull', False)), models.Q(('economic_exposure_weights_json__isnull', False), ('primary_economic_exposure__isnull', True)), _connector='OR'), name='chk_exposure_source'),
        ),
        migrations.AddConstraint(
            model_name='instrumenttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('yearly_fee_pct__isnull', True), ('yearly_fee_pct__gte', 0), _connector='OR'), name='chk_yearly_fee_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='instrumenttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('performance_fee_pct__isnull', True), ('performance_fee_pct__gte', 0), _connector='OR'), name='chk_performance_fee_non_negative'),
        ),
    ]
