# Generated by Django 6.0.3 on 2026-04-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0003_add_precious_metals_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='economicexposure',
            name='exposure_group',
            field=models.CharField(choices=[('fixed_income', 'Fixed Income'), ('equity', 'Equity'), ('real_estate', 'Real Estate'), ('crypto', 'Crypto'), ('precious_metals', 'Precious Metals'), ('undetermined', 'Undetermined')], max_length=32),
        ),
    ]
