# Generated by Django 6.0.3 on 2026-04-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refdata', '0004_add_undetermined_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttemplate',
            name='withdrawal_days',
            field=models.IntegerField(blank=True, help_text='Withdrawal/redemption days (T+N). E.g., 0=same day, 1=T+1, 30=T+30.', null=True),
        ),
    ]
