SCHEMA = {
    'api_version': 'v1',
    'description': (
        'Portfolio X-Ray reference data API. This API manages 5 reference tables '
        'used by a deterministic mechanical service that expands portfolio positions '
        'into structured precursors for downstream AI report generators.'
    ),
    'tables': {
        'economic_exposure': {
            'endpoint': '/api/v1/economic-exposures/',
            'lookup_field': 'exposure_code',
            'description': 'Economic substance taxonomy for diversification, risk, and performance.',
            'fields': {
                'exposure_code': {'type': 'string', 'max_length': 64, 'required': True, 'immutable': True,
                                  'description': 'Unique snake_case identifier. Cannot be changed after creation.'},
                'name': {'type': 'string', 'max_length': 255, 'required': True},
                'exposure_group': {'type': 'choice', 'required': True,
                                   'choices': ['fixed_income', 'equity', 'real_estate', 'crypto']},
                'description': {'type': 'text', 'required': False},
                'instructions_diversification': {'type': 'text', 'required': False, 'angle': 'diversification'},
                'instructions_liquidity': {'type': 'text', 'required': False, 'angle': 'liquidity'},
                'instructions_fees': {'type': 'text', 'required': False, 'angle': 'fees'},
                'instructions_tax': {'type': 'text', 'required': False, 'angle': 'tax'},
                'instructions_risk': {'type': 'text', 'required': False, 'angle': 'risk'},
                'instructions_performance': {'type': 'text', 'required': False, 'angle': 'performance'},
                'active': {'type': 'boolean', 'default': True},
                'created_at': {'type': 'datetime', 'read_only': True},
                'updated_at': {'type': 'datetime', 'read_only': True},
            },
            'filters': ['search', 'active', 'exposure_group', 'ordering'],
        },
        'tax_profile': {
            'endpoint': '/api/v1/tax-profiles/',
            'lookup_field': 'tax_profile_code',
            'description': 'Simplified tax treatment taxonomy.',
            'fields': {
                'tax_profile_code': {'type': 'string', 'max_length': 64, 'required': True, 'immutable': True},
                'name': {'type': 'string', 'max_length': 255, 'required': True},
                'description': {'type': 'text', 'required': False},
                'instructions_diversification': {'type': 'text', 'required': False, 'angle': 'diversification'},
                'instructions_liquidity': {'type': 'text', 'required': False, 'angle': 'liquidity'},
                'instructions_fees': {'type': 'text', 'required': False, 'angle': 'fees'},
                'instructions_tax': {'type': 'text', 'required': False, 'angle': 'tax'},
                'instructions_risk': {'type': 'text', 'required': False, 'angle': 'risk'},
                'instructions_performance': {'type': 'text', 'required': False, 'angle': 'performance'},
                'active': {'type': 'boolean', 'default': True},
                'created_at': {'type': 'datetime', 'read_only': True},
                'updated_at': {'type': 'datetime', 'read_only': True},
            },
            'filters': ['search', 'active', 'ordering'],
        },
        'issuer_type': {
            'endpoint': '/api/v1/issuer-types/',
            'lookup_field': 'issuer_type_code',
            'description': 'Issuer family taxonomy for concentration and diversification.',
            'fields': {
                'issuer_type_code': {'type': 'string', 'max_length': 64, 'required': True, 'immutable': True},
                'name': {'type': 'string', 'max_length': 255, 'required': True},
                'description': {'type': 'text', 'required': False},
                'instructions_diversification': {'type': 'text', 'required': False, 'angle': 'diversification'},
                'instructions_liquidity': {'type': 'text', 'required': False, 'angle': 'liquidity'},
                'instructions_fees': {'type': 'text', 'required': False, 'angle': 'fees'},
                'instructions_tax': {'type': 'text', 'required': False, 'angle': 'tax'},
                'instructions_risk': {'type': 'text', 'required': False, 'angle': 'risk'},
                'instructions_performance': {'type': 'text', 'required': False, 'angle': 'performance'},
                'active': {'type': 'boolean', 'default': True},
                'created_at': {'type': 'datetime', 'read_only': True},
                'updated_at': {'type': 'datetime', 'read_only': True},
            },
            'filters': ['search', 'active', 'ordering'],
        },
        'issuer': {
            'endpoint': '/api/v1/issuers/',
            'lookup_field': 'issuer_code',
            'description': 'Concrete issuer reference. Each belongs to one issuer_type.',
            'fields': {
                'issuer_code': {'type': 'string', 'max_length': 64, 'required': True, 'immutable': True},
                'name': {'type': 'string', 'max_length': 255, 'required': True},
                'issuer_type_code': {'type': 'foreign_key', 'required': True, 'references': 'issuer_type',
                                     'accept': 'issuer_type_code string',
                                     'returns': {'issuer_type_code': 'string', 'name': 'string'}},
                'description': {'type': 'text', 'required': False},
                'instructions_diversification': {'type': 'text', 'required': False, 'angle': 'diversification'},
                'instructions_liquidity': {'type': 'text', 'required': False, 'angle': 'liquidity'},
                'instructions_fees': {'type': 'text', 'required': False, 'angle': 'fees'},
                'instructions_tax': {'type': 'text', 'required': False, 'angle': 'tax'},
                'instructions_risk': {'type': 'text', 'required': False, 'angle': 'risk'},
                'instructions_performance': {'type': 'text', 'required': False, 'angle': 'performance'},
                'active': {'type': 'boolean', 'default': True},
                'created_at': {'type': 'datetime', 'read_only': True},
                'updated_at': {'type': 'datetime', 'read_only': True},
            },
            'filters': ['search', 'active', 'issuer_type_code', 'ordering'],
        },
        'instrument_template': {
            'endpoint': '/api/v1/instrument-templates/',
            'lookup_field': 'template_code',
            'description': 'Canonical resolved asset template. Core table of the system.',
            'fields': {
                'template_code': {'type': 'string', 'max_length': 64, 'required': True, 'immutable': True},
                'instrument_kind': {'type': 'choice', 'required': True,
                                    'choices': ['listed', 'fixed_income', 'fund', 'crypto', 'other']},
                'short_name': {'type': 'string', 'max_length': 255, 'required': True},
                'long_name': {'type': 'string', 'max_length': 512, 'required': False},
                'cnpj': {'type': 'string', 'max_length': 32, 'required': False},
                'b3_listed': {'type': 'boolean', 'required': False, 'nullable': True},
                'is_bdr': {'type': 'boolean', 'required': False, 'nullable': True},
                'yearly_fee_pct': {'type': 'decimal', 'required': False, 'nullable': True,
                                   'description': 'Non-negative decimal, 4 decimal places.'},
                'performance_fee_pct': {'type': 'decimal', 'required': False, 'nullable': True},
                'has_fgc': {'type': 'boolean', 'required': False, 'nullable': True},
                'requires_expiry_date': {'type': 'boolean', 'required': True, 'default': False},
                'requires_issuer_or_issuer_type': {'type': 'boolean', 'required': True, 'default': False},
                'primary_economic_exposure_code': {
                    'type': 'foreign_key', 'required': False, 'nullable': True,
                    'references': 'economic_exposure', 'accept': 'exposure_code string',
                    'description': 'Mutually exclusive with economic_exposure_weights_json.',
                },
                'economic_exposure_weights_json': {
                    'type': 'json_object', 'required': False, 'nullable': True,
                    'description': 'Map of exposure_code -> weight. Keys must be valid active codes. Weights must sum to 1.0. Mutually exclusive with primary_economic_exposure_code.',
                },
                'tax_profile_code': {'type': 'foreign_key', 'required': True,
                                     'references': 'tax_profile', 'accept': 'tax_profile_code string'},
                'primary_issuer_type_code': {
                    'type': 'foreign_key', 'required': False, 'nullable': True,
                    'references': 'issuer_type', 'accept': 'issuer_type_code string',
                },
                'issuer_type_weights_json': {
                    'type': 'json_object', 'required': False, 'nullable': True,
                    'description': 'Map of issuer_type_code -> weight. Same rules as exposure weights.',
                },
                'issuer_code': {
                    'type': 'foreign_key', 'required': False, 'nullable': True,
                    'references': 'issuer', 'accept': 'issuer_code string',
                },
                'instructions_diversification': {'type': 'text', 'required': False, 'angle': 'diversification'},
                'instructions_liquidity': {'type': 'text', 'required': False, 'angle': 'liquidity'},
                'instructions_fees': {'type': 'text', 'required': False, 'angle': 'fees'},
                'instructions_tax': {'type': 'text', 'required': False, 'angle': 'tax'},
                'instructions_risk': {'type': 'text', 'required': False, 'angle': 'risk'},
                'instructions_performance': {'type': 'text', 'required': False, 'angle': 'performance'},
                'active': {'type': 'boolean', 'default': True},
                'created_at': {'type': 'datetime', 'read_only': True},
                'updated_at': {'type': 'datetime', 'read_only': True},
            },
            'constraints': [
                'Exactly one of primary_economic_exposure_code or economic_exposure_weights_json must be present.',
                'Weighted JSON keys must be valid active codes and weights must sum to 1.0 (tolerance 0.0005).',
                'yearly_fee_pct and performance_fee_pct must be non-negative if present.',
            ],
            'filters': ['search', 'active', 'instrument_kind', 'tax_profile_code',
                        'primary_economic_exposure_code', 'issuer_code',
                        'b3_listed', 'is_bdr', 'has_fgc', 'requires_expiry_date', 'ordering'],
        },
    },
    'angles': ['diversification', 'liquidity', 'fees', 'tax', 'risk', 'performance'],
    'batch_endpoints': {
        'instructions': {
            'endpoint': '/api/v1/batch/instructions/',
            'method': 'PATCH',
            'description': 'Atomically update instruction text for one angle across multiple records.',
            'request_format': {
                'angle': 'one of the 6 angles',
                'updates': [{'table': 'table_name', 'code': 'record_code', 'text': 'instruction text or null'}],
            },
        },
    },
    'special_endpoints': {
        'schema': {'endpoint': '/api/v1/schema/', 'method': 'GET', 'description': 'This endpoint.'},
        'health': {'endpoint': '/api/v1/health/references/', 'method': 'GET',
                   'description': 'Reference data consistency checks.'},
    },
    'conventions': {
        'codes': 'All codes are lowercase snake_case, immutable after creation.',
        'deletion': 'No DELETE endpoints. Use PATCH {"active": false} to deactivate.',
        'idempotent_post': 'POST with an existing code returns 409 with the existing record.',
        'fk_on_write': 'Foreign keys are submitted as code strings (e.g., "tax_profile_code": "general").',
        'fk_on_read': 'Foreign keys are returned as nested objects with code and name.',
        'pagination': 'All list endpoints are paginated. Use page and page_size query params.',
    },
}
